key-store: fix getVar() missing positional argument
TypeError: getVar() missing 1 required positional argument: 'expand'

Signed-off-by: Wenzong Fan <wenzong.fan@windriver.com>